GET http://localhost:3000/api/flowers

###

GET http://localhost:3000/api/flowers/1

###

POST http://localhost:3000/api/flowers/
Content-Type: application/json

{
    "flowerName": "Flower",
    "description": "Pretty",
    "color": "White"
}

###

PUT http://localhost:3000/api/flowers/10
Content-Type: application/json

{
    "flowerName": "Ogräs",
    "description": "fuuul",
    "color": "brun"
}

###

DELETE http://localhost:3000/api/flowers/11

###
