GET http://localhost:3000/api

###

GET http://localhost:3000/api/2

###

POST http://localhost:3000/api/
Content-Type: application/json

{
    "bloo": "lol",
    "description": "fin fin fin",
    "color": "vit"
}

###

PUT http://localhost:3000/api/flowers/1
Content-Type: application/json

{
    "flowerName": "Ogräs",
    "description": "fuuul",
    "color": "brun"
}

###

DELETE http://localhost:3000/api/flowers/0

###
